/* Ironlog service worker. Generated by scripts/build.js; do not edit. */
const CACHE="ironlog-2026.10.07-r32-c11f48d66b";
const FILES=["./","index.html","manifest.webmanifest","fonts/fonts.css","fonts/big-shoulders-display-latin-600-normal.woff2","fonts/big-shoulders-display-latin-700-normal.woff2","fonts/big-shoulders-display-latin-800-normal.woff2","fonts/hanken-grotesk-latin-400-normal.woff2","fonts/hanken-grotesk-latin-500-normal.woff2","fonts/hanken-grotesk-latin-600-normal.woff2","fonts/hanken-grotesk-latin-700-normal.woff2","vendor/chart.umd.js","vendor/Sortable.min.js","vendor/three.module.min.js","vendor/supabase.js","cloud.js","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-512.png","icons/apple-touch-icon.png","icons/favicon-64.png"];
/* A first install takes over at once. An update installs and then waits until
   the page says the lifter tapped Reload (or every window of the app has
   closed), so a version never changes under a session in progress.
   Files are fetched past the browser's HTTP cache: GitHub Pages lets a file be
   cached for 10 minutes, so a plain fetch right after a publish could store
   the previous index.html under the new version's name. */
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES.map(f=>new Request(f,{cache:'reload'})))));});
self.addEventListener('message',e=>{if(e.data==='skipWaiting')self.skipWaiting();});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k.startsWith("ironlog-")&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
/* Same-site files come from this version's cache, so the app opens instantly
   and offline, and the page always matches the files cached with it. A new
   version arrives only as a new worker with its own cache (the name carries a
   hash of every file), never by rewriting this one. Other sites (the CDN
   fallbacks) go to the network untouched, and so does the preview build under
   preview/: it has its own worker, which the preview page can only install
   if this one lets the page load. */
const OWN=new URL('./',self.registration.scope).pathname;
self.addEventListener('fetch',e=>{
  const r=e.request;if(r.method!=='GET')return;
  const u=new URL(r.url);if(u.origin!==location.origin)return;
  if(u.pathname.startsWith(OWN+'preview/'))return;
  if(r.mode==='navigate'){
    e.respondWith(caches.open(CACHE).then(async c=>(await c.match('index.html'))||fetch(r).catch(()=>new Response('Offline',{status:503}))));
    return;
  }
  e.respondWith(caches.match(r,{ignoreSearch:true}).then(hit=>hit||fetch(r)));
});
