/* Ironlog service worker. Generated by scripts/build.js; do not edit. */
const CACHE="ironlog-2026.09.27-r15-29b8737773";
const FILES=["./","index.html","manifest.webmanifest","fonts/fonts.css","fonts/big-shoulders-display-latin-600-normal.woff2","fonts/big-shoulders-display-latin-700-normal.woff2","fonts/big-shoulders-display-latin-800-normal.woff2","fonts/hanken-grotesk-latin-400-normal.woff2","fonts/hanken-grotesk-latin-500-normal.woff2","fonts/hanken-grotesk-latin-600-normal.woff2","fonts/hanken-grotesk-latin-700-normal.woff2","vendor/chart.umd.js","vendor/Sortable.min.js","icons/icon-192.png","icons/icon-512.png","icons/icon-maskable-512.png","icons/apple-touch-icon.png","icons/favicon-64.png"];
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(FILES)).then(()=>self.skipWaiting()));});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(ks=>Promise.all(ks.filter(k=>k.startsWith('ironlog-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
/* Same-site files come from the cache first, so the app opens instantly and
   offline. The page itself is also refreshed in the background, so a new
   version is picked up on the next launch. Other sites (the CDN fallbacks)
   go to the network untouched. */
self.addEventListener('fetch',e=>{
  const r=e.request;if(r.method!=='GET')return;
  const u=new URL(r.url);if(u.origin!==location.origin)return;
  if(r.mode==='navigate'){
    e.respondWith(caches.open(CACHE).then(async c=>{
      const hit=await c.match('index.html');
      const net=fetch(r).then(res=>{if(res&&res.ok)c.put('index.html',res.clone());return res;}).catch(()=>null);
      return hit||(await net)||new Response('Offline',{status:503});
    }));
    return;
  }
  e.respondWith(caches.match(r,{ignoreSearch:true}).then(hit=>hit||fetch(r)));
});
